### PR TITLE
Add centered image grid example

### PR DESCRIPTION
**Pull request by kriskowal**
This example illustrates how to translate and scale a unit square to fill the center of the window, then fills that unit square with lobsters in five ranks and files, using the forxy 2d iterator defined in modules/vec.lobster.

### CODE REVIEW

**Comment by aardappel** [comment]
Thanks! This example is pretty similar to the previous one though, not sure if showing how to put images in a grid is worth another example. Also I'd inline `center_unit_square` and use a comment instead, to make it easier to follow. Maybe the two examples can be merged such that the useful learnings can all be in one?

**Comment by kriskowal** [comment]
Yeah, I’m tracing my steps since it naturally progresses as another graduated tutorial. I’m tempted on one hand to combine these into a single example, but that risks obfuscating the primary insight.

Instead of landing this, I could queue up a sequence of elaborations for a sprites and tiles tutorial as I pick up a concept at a time, or drop it if it turns into a dead end.

**Comment by aardappel** [comment]
Or if its really a tutorial, add something similar to http://aardappel.github.io/lobster/shooter_tutorial.html :)

**Comment by kriskowal** [comment]
Indeed. I’ll see where this takes me.

**Pull request closed without merging**
